version: "3.9"
services:
  postgresc1:
    container_name: postgresc1
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "postgre_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    hostname: postgres
    restart: always
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: adenon@adenon.com
      PGADMIN_DEFAULT_PASSWORD: 123456
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8081:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.233.1.0/24
volumes:
  postgre_data:
  pgadmin-data: